### ISSUE TITLE
PriceRangeFilter should not be built on top of SelectField

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor-storefront#126]
We should get rid of `<SelectField />` component in `<PriceRangeFilter />` because it's a messed up hack that should not be used in the open source project. Instead, we should build its own component with its own styles.

**Comment by Moomboh** [comment]
I'd like to take this on as my first ever opensource issue.
So if I understand it correctly `<PriceRangeFilter />` should have similiar appearance like the other `<SelectField />` based Filters without using the current `<SelectField />` hack.
Also I want to implement some ideas of #188.
Maybe it is even sensible to get rid of the dropdown for the `<PriceRangeFilter />` completely and show only a range-slider instead since it will take up the same space for the UI-Elements regardless of the size of the price-range contrary to other filters which can be long lists with varying number of options and therefore actually need a dropdown.
