### ISSUE TITLE
Implement RazorPay gateway

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor-storefront#147]
After merging https://github.com/mirumee/saleor/pull/3205

We will have a new payment gateway available - RazorPay.
We should include it in our new storefront.

Docs:
https://docs.razorpay.com/

**Comment by maarcingebala** [comment]
Currently, there is one gateway hardcoded, so we have to generally implement support for gateways that are available in API. There is an [issue for that in the backend ](https://github.com/mirumee/saleor/issues/3617). I'll open a new issue for that.

**Comment by maarcingebala** [comment]
Actually we have an issue already: #208.

**Comment by NyanKiyoshi** [comment]
Are we still going to implement the razorpay gateway? Any idea/ leads yet on how we will proceed?

I will open an issue in Saleor whenever I have some free time to do so. It's going to be a huge wall of text. To summarize, the sandbox mode of razorpay is **no longer** respecting their documentation. They introduced a bug in their backend, I have been battling with their support for two weeks now, they are refusing to acknowledge the bug, instead, they show it as a feature, despite the documentation seeing otherwise.

The checkout process of Razorpay should be fine on the live API (cannot verify as I'm not a business owner, and they refuse to give me access to a dummy account). Only bugged in sandbox mode.

I will take the matter into my hands in Saleor, a provide a fix. But may won't happen until a few months. So be aware, you may not want to go for their javascript checkout library without making changes to their code/ process.

I will try to open a detailed issue in Saleor on this matter during this week.

**Comment by pankaj28843** [comment]
Hey,

I have been customizing Saleor for an Indian company. I added support for Razorpay in the storefront as it was missing.

I am using [Standard Checkout of Razorflow]() which has this [payment flow](https://razorpay.com/docs/payment-gateway/payment-flow/)

Here are my changes:
 - in [saleor-storefront](https://github.com/PyFoxTech/saleor-storefront/commit/582871c244b6027d46d47939ba336a9a1a8d5d32)
- in [saleor](https://github.com/PyFoxTech/saleor/commit/022d5d5fbf264743799b83dd3914932c89746d9d)

My code changes are bit hacky as I did it in just 2 days while trying to figure out payment flow between storefront and Saleor via GraphQL.

I would like to help in adding Razorflow integration to the storefront.

Who do I need to talk to for this?

**Comment by maarcingebala** [comment]
@orzechdev @krzysztofwolski When you have time you could take a look at this.

**Comment by manishladkat29** [comment]
@pankaj28843 Did you get to a trusted solution for the razor pay integration?

**Comment by rawho** [comment]
@pankaj28843 have you done any modification to the code to make it more secure

**Comment by Shubhra1028** [comment]
> Hey,
> 
> I have been customizing Saleor for an Indian company. I added support for Razorpay in the storefront as it was missing.
> 
> I am using Standard Checkout of Razorflow which has this [payment flow](https://razorpay.com/docs/payment-gateway/payment-flow/)
> 
> Here are my changes:
> 
> * in [saleor-storefront](https://github.com/PyFoxTech/saleor-storefront/commit/582871c244b6027d46d47939ba336a9a1a8d5d32)
> * in [saleor](https://github.com/PyFoxTech/saleor/commit/022d5d5fbf264743799b83dd3914932c89746d9d)
> 
> My code changes are bit hacky as I did it in just 2 days while trying to figure out payment flow between storefront and Saleor via GraphQL.
> 
> I would like to help in adding Razorflow integration to the storefront.
> 
> Who do I need to talk to for this?

These api's seems to be deperecated in saleor 2.11. Any way to implement razorpay in storefront 2.11?

**Comment by mathur619** [comment]
> > Hey,
> > I have been customizing Saleor for an Indian company. I added support for Razorpay in the storefront as it was missing.
> > I am using Standard Checkout of Razorflow which has this [payment flow](https://razorpay.com/docs/payment-gateway/payment-flow/)
> > Here are my changes:
> > 
> > * in [saleor-storefront](https://github.com/PyFoxTech/saleor-storefront/commit/582871c244b6027d46d47939ba336a9a1a8d5d32)
> > * in [saleor](https://github.com/PyFoxTech/saleor/commit/022d5d5fbf264743799b83dd3914932c89746d9d)
> > 
> > My code changes are bit hacky as I did it in just 2 days while trying to figure out payment flow between storefront and Saleor via GraphQL.
> > I would like to help in adding Razorflow integration to the storefront.
> > Who do I need to talk to for this?
> 
> These api's seems to be deperecated in saleor 2.11. Any way to implement razorpay in storefront 2.11?

Hey, were you able to implement razorpay in saleor storefront 2.11?

**Comment by JimGeek** [comment]
@pankaj28843 Have you got time to integrate your solution into storefront ? 
@maarcingebala Please help with this.

**Comment by CuriousLearner** [comment]
Hi @pankaj28843 I saw your implementation on Saleor 2. Thanks for your contribution!

 Is there any chance you'll be porting this to the new version of Saleor?

**Comment by pankaj28843** [comment]
@CuriousLearner I have a production website with razorpay integration for Saleor 2.11. I am not working regularly on it though, and, I don't think I would be able to contribute back right now.

**Comment by CuriousLearner** [comment]
Ok, thanks for the update Pankaj! 🙌🏻 

Hey @maarcingebala & @NyanKiyoshi 👋🏻 

Will it make sense now to add this long awaited feature in the storefront? (This can also be then ported to the new react-storefront being built), but most importantly will act as a reference implementation.

I tried to port Pankaj's patch on storefront, but seems like a lot of styling and components have been changed and I was stuck. I'm comfortable with Python/Django but don't know React (just did a few tutorials to make sense of the patch that Pankaj initially worked on), so if needed, I can help with any changes needed on the saleor core repo.

Please let me know.

Many thanks!

**Comment by maarcingebala** [comment]
Hey @CuriousLearner, this saleor-storefront is not maintained anymore as we are moving to react-storefront now. We're also looking into rewriting all payment integrations as Saleor Apps this year, and because of that, I wouldn't invest time into the current implementation of RazorPay in Saleor. We'll be building similar integrations for other payment gateways and releasing them as references for the community to build their own integrations.

**Comment by CuriousLearner** [comment]
Ok, that sounds good! Thanks @maarcingebala 🙌🏻

**Comment by parthlawate** [comment]
Is there a reference already that can be used to build new integrations ? Would Stripe be a good one ?
