### ISSUE TITLE
Payment with Mollie 

### ISSUE THREAD

**Issue by officerebel** [mirumee/saleor-storefront#177]
### What I'm trying to achieve
I try to implement Mollie And test it in the backend and the PWA

### Describe a proposed solution
A guideline where to start a) test payment without the mollie
B guideline how to start adding the API and where
C guideline how to start testing with payments with the mollie api

### Other solutions I've tried and won't work
Found a mollie and Django Oscar Mollie API but don't know where to start. 
Installed the front-end on port 8000 and the PWA on 3001 ( Kibana isolates the port 3000).
When visiting the PWA there is no payment gateway in the end both the order visible.
Could not find in the documentation how to use a demo payment wich works both on the backend on port 8000 and on the PWA on port 3001 (3000 in most cases and in dev).

**Comment by maarcingebala** [comment]
I'd recommend getting familiar with these resources:
- https://github.com/mirumee/saleor/pull/3408 - recent PR that added Stripe payments to Saleor, may be used as an inspiration and help to see what and where needs to be added
- http://docs.getsaleor.com/en/latest/guides/payments.html - sections in our docs about adding new payment gateways.

At the moment payments are a bit unstable as we're doing some refactoring in order to move each payment gateway to a separate library ([see this issue](https://github.com/mirumee/saleor/issues/3422)), which means that the architecture is likely to change. But even if you implemented a working proof-of-concept of integration with Mollie, it should be fairly easy to port it to the new architecture later.

**Comment by officerebel** [comment]
Thank for your reply. Wat is not clear to me is how to start?  Should I dig into the code of mirumee/saleor#3408 and implement it in my local repo? Of combine the two with as a new payment method like https://docs.getsaleor.com/en/latest/guides/payments.html. Like you said read and make a image of how it combines? Or is there an more easy way? 😬

**Comment by maarcingebala** [comment]
I'd start with adding a new module for your integration: `saleor/payment/gateways/mollie/__init__.py`. If you look at every other gateway we have, we put all the core logic functions into those `__init__.py` files. The docs section I linked above explains what functions should each payment gateway implement (e.g. `authorize`, `capture` etc.).

If you want to provide support for the Django-based storefrontm, you'd need to provide a Django form to process payment. See e.g. `braintree/forms.py` for details. On the other hand, if you're aiming to use the PWA storefront (from this repository) you should rather make sure that your payment gateway works with our API.

**Comment by lexvz** [comment]
Hi!

@officerebel, have you managed to get Mollie to work?

Thanks in advance!
