### ISSUE TITLE
Restore user checkout on login

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-storefront#219]
When user logs in we should fetch his last checkout and if it is available, restore the cart based on that.

Last checkout is available in the `User` type: 

```
{
  me {
    checkout {
      ...
    }
  }
}
```
also might be useful
```
mutation {
  tokenCreate(...) {
    user {
      checkout {
        ...
      }
    }
  }
}
```

**Comment by jxltom** [comment]
One more thing is that if the guest has a cart already, the cart should assign to the customer by ```CheckoutCustomerAttach``` when customer login.

**Comment by maarcingebala** [comment]
Right. We were discussing how should we approach that and we don't want to implement any kind of merging logic for carts. I've heard that django-oscar implements that and one of our past project based on that framework used it and this was a total mess. Instead, we should always treat the "newest" cart as the actual one.

So the logic would be as follows:

Guest user logs in
1) If the user has a cart in local storage, we take it as the newest one and ignore the one coming from API.
2) If the user has no cart in local storage, we take whatever came from API and recreate the cart based on that. If empty checkout was returned from API, we ignore it.

⬆️ This should probably go into some general documentation for our storefront as part of explanation of how our checkout works.

**Comment by jxltom** [comment]
@maarcingebala In step 1, should we also assign the valid cart to user when login? This can sync the cart and then the login user can always have same cart when they sign in in different devices.

Besids, do you mind enlighten me what kind of mess it is for merging logic? I didn't thought about it thoroughly but it sounds fine in the first thought. Thanks!

**Comment by jxltom** [comment]
@mociepka Thanks a lot for sharing these valuable experiences! I agree with most of them, though I have a few concerns.

> 2. The user experience issue.

This is true, but there is an another issue. Imaging that a guest without login adds a lot of favorite products to cart, and then he/she decicdes to buy and login. Without the merging logic, he/she finds the cart after login is empty! The customer needs to find all products and add them back. This feels very frustrated.

> Do we need to store all carts? Our answer is NO.

This is fine to backend, but it is hard to implement it in frontend, such as in storefront 2.0 or any mobile apps based on saleor's backend API. A customer can add products to cart (which is checkout in saleor) without providing a email. If this cart(checkout) is not stored in backend, how the frontend implement the cart logic, such as checking the stocks/avaliablity and calculate the total prices which shows to customers. I know this can be implement in frontend, but it requires a lot of code. IMHO, it is more suitable to be implemented in backend.

**Comment by mociepka** [comment]
> Imaging that a guest without login adds a lot of favorite products to cart, and then he/she decicdes to buy and login. Without the merging logic, he/she finds the cart after login is empty!

This scenario is covered by point 2. We won't create a new cart when a user logs in, we will use the existing anonymous cart (that cart won't be anonymous anymore after user logs in). If the user had an old cart connected with profile we won't use or merge it (it will be treated as abandoned one).

So the assumption is that after login, nothing happens with user cart. It stays the same.

> how the frontend implement the cart logic, such as checking the stocks/avaliablity and calculating the total prices which is shown to customers

We introduce GraphQL and SPA because we want to transform Saleor into a reach PWA e-commerce system. In PWA offline support is crucial. Because of that a cart need to be stored inside the client app. The goal is to allow users to browse the catalog and create baskets even in offline mode (in the future even do a checkout ;) ). In terms of availability (data synchronization between client and server), we again asked ourselves a question; what is the main scenario? In the main scenario, we assumed that prices and availability won't change that often. So for corner cases like price changes products not available, we will just notify a user inside the app or email or push notification.

I know that everyone is thinking in a cart way, maybe we consider creating cart API @maarcingebala ? It could just work on the `Checkout` models. But the name will be in the API :).

> 2. Another reason is that checkouts without email are not useless all the time since they might be attached to a user

I mentioned that case in point 1: 
> if it has an email attached to it (either by a user or through anonymous checkout)

If user is attached email shpuld be always saved inside checkout object.
