### ISSUE TITLE
Add a milestone/project for the next release

### ISSUE THREAD

**Issue by mridang** [mirumee/saleor-storefront#276]
The last release was 0.4.0. Is there any plans to add a new milestone/project for the next release? It would be handy to see the progression of the release and the issues to be done for the release. Thank you.

**Comment by maarcingebala** [comment]
Hey @mridang, next week we'll release a new version 0.5.0 - you can read about incoming changes in the changelog file.

As for the next milestones, I didn't plan it yet, because we had to switch over to a different project for some time and we're reorganizing our teams a bit. Unfortunately, that's the case for open-source projects that we're not able to work on them full-time always.

But don't worry - we have big plans about this project and in a week or two I hope I'll be able to give you a more specific update our plans :) What we wanted to focus on next is user profile page, address management, list of user's orders.

**Comment by mridang** [comment]
Thank you Marcin.
