### ISSUE TITLE
Variant picker component

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor-storefront#36]
![image](https://user-images.githubusercontent.com/1870738/45105504-ad608600-b134-11e8-8b41-8cc55c1a8b0a.png)

## Api limitations 
Current Saleor API doesn't allow to set colors or images on the attribute field. Introduction of new attribute field `value` will solve this issue (more info in the https://github.com/mirumee/saleor/issues/2793). Because of this limitation, we will use the name field as a name and value.

```graphql
query Product {
  product(id: "UHJvZHVjdDo0") {
    id
    variants {
      edges {
        node {
          id
          sku
          name
          attributes {
            attribute {
              id
              slug
              name
            }
            value {
              id
              name
              value:name
            }
          }
        }
      }
    }
  }
}
```

If the value matches color (`#(?:[0-9a-f]{2}){2,4}|#[0-9a-f]{3} `or even more hardcore https://gist.github.com/olmokramer/82ccce673f86db7cda5e#gistcomment-2174868) or image (`(https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*))`) we should render it as a block option picker, if not as normal select.

## Variant dimensions simplification
Another simplification. Saleor gives you the ability to define more than two attributes per variant that complicates UX a little bit. To keep it simple we will combine all above the first attribute to one abstract one.

### Trousers example:

Trouser variant is defined by three attributes:
* color: `#999098`, `#af9098`,
* height: 32, 34, 36
* width: 32, 33

we will flatten this structure to two dimentsion color, height/width:
* color: `#999098`, `#af9098`,
* height/width: 32/33, 32/33, 34/32, 36/33

**Comment by f00wl** [comment]
Hi, I'm trying to get working a color picker as a product variant attribute in the Saleor storefront.

more-less like describe in this issue :
![colorpicker](https://user-images.githubusercontent.com/1870738/45105504-ad608600-b134-11e8-8b41-8cc55c1a8b0a.png)

 I'm a bit confusing about how to get this feature working.
After looking at https://github.com/mirumee/saleor/issues/2793 implemented in [this comit](https://github.com/mirumee/saleor/commit/e332a0e03f25b9b5f56570fca67179451d5e505d) it seems that setting value of an attribute to something like `#ACABAC` or `rgb(131,213,121)` should use the backed feature automatically, but I still not understand how to work with.

Also I searched in the code for the  `ProductAttribuetValueType` and I only get the migration associated with. The code refactoring finished to lost me :confused: 

I'm not a React dev and fronted is not my best, is anyone could help me on this ?
Thanks for your time.

**Comment by maarcingebala** [comment]
Hey, I'm afraid it won't be possible to implement it in the frontend since it requires backend changes. `ProductAttributeValueType` that you found was our first idea about how to store colors or different data types for attribute values, but it was never fully implemented in the dashboard or in the storefront. 

In Saleor 2.9.0 we added so-called "enterprise-grade attributes" which largely extends how the attributes behave, and one part of this feature are input types for attributes values. So far we have only two types: single-select and multi-select text inputs. In our backlog, we have the issue https://github.com/mirumee/saleor/issues/5036 to add more and color input types is one of them. 

If you wanted to implement it now, I think you would have to either customize the backend to store the additional RGB colors somehow or wait for the 2.10 release (planned for April 2020) where we'll officially release Metadata API that allows you to store arbitrary key-value pairs on many objects.

**Comment by f00wl** [comment]
Thanks very much for your answer. It could be very useful to have this available outside of "entreprise-grade" but unfortunately I understand your point. I will wait for the april release and see how to do this with Metadata API. If it doesn't I will probably implement it myself using ideas found in the project backlog.
