### ISSUE TITLE
bad HTTP response code in Storefront

### ISSUE THREAD

**Issue by heiqs** [mirumee/saleor-storefront#375]
When I connect to the storefront and do inspection with the browser, I see the following errors:

A bad HTTP response code (404) was received when fetching the script.
account:1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.

I even refresh/restart the storefront but didn't help.

**Comment by jwm0** [comment]
This is due to service worker being disabled in the default webpack dev mode. If you wish to turn this feature on in dev mode (it's auto-enabled on production builds) use `npm run start:worker` instead of `npm run start`. This should get rid off the service worker error but bear in mind that the service worker is doing some caching underneath and you might need to refresh the app a couple of times to see the changes made to the code. That's why we don't use it in default dev mode.
