### ISSUE TITLE
Show image placeholders

### ISSUE THREAD

**Issue by bogdal** [mirumee/saleor-storefront#489]
### What I'm trying to achieve

I want to see image placeholders when products/variants don't have thumbnails.

Ref https://github.com/mirumee/saleor/pull/4812

### Describe a proposed solution

Add `ImagePlaceholder` component and render it when there is no thumbnail image.

**Comment by xit4** [comment]
I checked the code and I found that:
1- In case the url is unreachable 
```
{
"id": "UHJvZHVjdDo4Mw==",
  "name": "Seaman Lager",
  "thumbnail": {
    "url": "https://fake-url.png",
    "alt": "",
  },
  "thumbnail2x": {
    "url": "https://fake-url.png",
  },
...
}
```
the `CachedImage` component handles the problem by setting the unavailability flag to true which cause it to render the placeholder image
2- In case the entire thumbnail property is null
```
{
"id": "UHJvZHVjdDo4Mw==",
  "name": "Seaman Lager",
  "thumbnail": null,
  "thumbnail2x": null,
...
}
```
the `Thumbnail` component handles the problem by wrapping `source.thumbnail.url` with a `maybe()` call. `CachedImage` receives `undefined` (returned by `maybe` in case of catched exceptions) and falls back to render the placeholder.

I'm assuming the issue here is about handling the matter in a more declarative way, meaning the `Thumbnail` component should check the existence of a thumbnail and return the placeholder image instead of `CachedImage`
