### ISSUE TITLE
Preselect a variant on the product page

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-storefront#625]
When opening the product details page we should preselect a variant for the user to make the "Add to basket" button active from the beginning. Now the button is disabled initially and you need to select anything from the variant picker to activate it. We could instead select the first variant available.

**Comment by krzysztofwolski** [comment]
Feature wont be implemented. Having variant preselected will lead to more mistakes. (For example add wrong, default product size to the cart).

Both zalando and asos don't choose sizes:
https://www.zalando.pl/levisr-levisrsuper-mario-the-trucker-jacket-kurtka-jeansowa-blue-denim-le221000c-k11.html

https://www.asos.com/pl/asos-design/asos-design-zigs-czarne-kapcie-z-haftowanym-wzorem/prd/13471583?clr=czarny-kolorowy&colourWayId=16544121&SearchQuery=&cid=6992

**Comment by dynamized** [comment]
In our use case, 99% of our products have only one variant.  In the rare case that the wrong color is selected the user will have time to review their order and catch the mistake.  For us there is a significant benefit to reducing the number of clicks to perform a checkout and this benefit outweighs the occasional mistaken color selection.  I'm in the process of learning React and TS to make these modifications.  Could someone help me preselect the first variant so that the "Add to basket" button is active on page load or at least explain what would need to be edited.  Thank you for any help.
