### ISSUE TITLE
Single value in attribute (in product page)

### ISSUE THREAD

**Issue by PiotrLaszczyk** [mirumee/saleor-storefront#667]
If there is only one value in variant attributes list user need to select it anyway just to enable "add to cart" button. I guest it should be selected by default as there is no other options in this scenario.

Additionally if there is more values maybe one of them should be selected by default also? Because actually "add to cart" button is dimmed which is confusing for users.

**Comment by pwgryglak** [comment]
Hi. Could you provide us an example of the first scenario you are describing? It's hard for me to imagine a configurable product that has an option with only one value. All I could think of is a configurable product and use the mentioned attribute as product attribute rather than variant attribute.

Regarding the default value - We wanted to remove the possibility for ordering wrong variant of the product. There is a possibility that customer would order product without checking whether correct values were selected and return the product afterwards. It is easily avoidable if they have to select those values each time they go to product page. 

Thanks for feedback.

**Comment by PiotrLaszczyk** [comment]
Idea of service I create is that multiple vendors may sell same product (like A... on did). Selection by EAN... and I have variant parameter: "delivery from" and customer may chose from who would like to buy products... sometimes products have only one supplier.. this is the case I mentioned.

Imagine that during time new suppliers may arrive or disapears... its easier to handle this by simply adding/removeing vendors to list existing. 

But sometimes product has only single supplier. I could remove this parameter from product. But then where is information who is supplier ;), or if new supplier arrive then haw to handle this...

As I said, its easier to handle this as list even with single parameter. 

---
But as I understand its for parameters like S, M, L, XL... Imagine that You want to handle this only by sw... no human between. You have product X which is being sold only in variant M.  You have only this in options... so You create product.... but how about variant attribute? If there is only M in You offer You simply create list with one option... then after 6 months You have three S, M, XL... so You add them to list..then producer resigns from XL, so You remove it from list... nice and simply....  its easy to handle situation when products and its variants changes during time.

**Comment by pwgryglak** [comment]
Thanks! That actually, it's a good point - we'll be looking at what we can do here. Thank you for your feedback and elaboration on your specific use case.
