### ISSUE TITLE
Missing PKG "@saleor/sdk"

### ISSUE THREAD

**Issue by Eslamspot** [mirumee/saleor-storefront#752]
There is missing PKG in last version make storefront all down.

### Screenshots
https://i.imgur.com/kFsku7V.png
https://i.imgur.com/wJB7mJo.png

**System information**
Docker

**Comment by dominik-zeglen** [comment]
We're on it. Meanwhile we recommend you to switch to non-docker development mode.

**Comment by patrys** [comment]
I don't think we recommend that but it is a possible workaround.

**Comment by Eslamspot** [comment]
Thanks team for your comments, Do you have workaround to pass this issue till we get it fixed?

**Comment by whidbeysea** [comment]
It is possible to switch from "Docker Installation" to "Manual Installation on Windows" as shown in the Documentation so that we can get a functional Storefront, and then still be able to deploy our customized application to our Production Web Server using Docker ? This issue is such a pain in the @$$!!!!

**Comment by Eslamspot** [comment]
I test this issue with Last resale and finally it's fixed, Thanks team for hard efforts.
