### ISSUE TITLE
Improve offline placeholder component

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor-storefront#92]
I just don't think that rendering `OFFLINE :(` is a good idea here.

**Comment by pwgryglak** [comment]
I've added placeholder component to the UI guide

**Comment by maarcingebala** [comment]
Currently, a page that hasn't loaded due to offline mode and missing data renders like that:
![image](https://user-images.githubusercontent.com/5421321/50091746-78bc9a00-020c-11e9-8769-afff93eb52f1.png)

@pwgryglak I can see on figma that we have a placeholder for missing image ("Photo unavailable"). Are you referring to that one or is there any other design for an entire page that is unavailable due to offline?

**Comment by pwgryglak** [comment]
@maarcingebala 
If you're referring to placeholder image you can find in storefront UI guide then it is the one to use yes. No there is no specific page referring to missing images. If you need it I can prepare it.

**Comment by maarcingebala** [comment]
Shuold be fixed now.
